image: gitlab.sc.ulb.ac.be/smartcampus/dependency_proxy/containers/jlandercy/python-challenge:1.1

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: "Cache_${CI_PROJECT_ID}"
  paths:
    - .cache/pip

default:
  before_script:
    - python3 -m virtualenv --system-site-packages venv
    - source venv/bin/activate
    - python3 -m pip install --user -r requirements.txt

stages:
  - build
  - tests
  - docs

package:
  stage: build
  tags:
    - build
  script:
    - python setup.py sdist bdist_wheel
    - python -m pip install ./dist/*.whl
  artifacts:
    expire_in: 1 week
    paths:
      - dist

quality:
  stage: tests
  tags:
    - tests
  needs:
    - package
  script:
    - nox --session tests linter coverage typehints
  artifacts:
    expire_in: 1 week
    paths:
      - .cache/reports/*
    reports:
      junit:
        - .cache/reports/unittest.xml

notebooks:
  stage: tests
  tags:
    - tests
  needs:
    - package
  allow_failure: true
  script:
    - nox --session notebooks
  artifacts:
    expire_in: 1 week
    paths:
      - ./docs/source/notebooks/*
      - .cache/reports/notebooks.log

documentation:
  stage: docs
  tags:
    - docs
  needs:
    - quality
    - notebooks
  script:
    - nox --session docs
  artifacts:
    expire_in: 1 week
    paths:
      - .cache/docs/*
